---
# tasks file for project2
- name: Enable nginx in amazon-linux-extras
  command: amazon-linux-extras enable nginx1
  args:
    creates: /etc/yum.repos.d/nginx.repo

- name: Clean yum metadata
  command: yum clean metadata

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Ensure Nginx web root exists
  file:
    path: /usr/share/nginx/html
    state: directory

- name: Remove default server config if present
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Ensure Nginx does not listen on port 80
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '^\s*listen\s+80;'
    replace: '# listen 80;'
    backup: yes

- name: Add custom server blocks to listen on ports {{ nginx_ports | join(', ') }}
  copy:
    dest: /etc/nginx/conf.d/ansible.conf
    content: |
      {% for port in nginx_ports %}
      server {
          listen {{ port }};
          server_name localhost;

          location / {
              root /usr/share/nginx/html;
              index index.html index.htm;
          }
      }
      {% endfor %}

- name: Deploy custom index.html
  copy:
    content: |
      <!DOCTYPE html>
      <html>
      <head><title>Nginx on Ports {{ nginx_ports | join(' and ') }}</title></head>
      <body><h1>Hello from Nginx on Ports {{ nginx_ports | join(' and ') }} (via Ansible)</h1></body>
      </html>
    dest: /usr/share/nginx/html/index.html

- name: Ensure port 80 is free before starting Nginx
  command: fuser -k 80/tcp
  ignore_errors: yes
  changed_when: false

- name: Validate Nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: "'successful' not in nginx_test.stderr"

- name: Start and enable Nginx
  service:
    name: nginx
    state: restarted
    enabled: true
  register: nginx_service
  ignore_errors: true

- name: Show Nginx service status if failed
  command: systemctl status nginx
  when: nginx_service.failed
  register: nginx_status_output
  ignore_errors: true

- name: Debug Nginx service status
  debug:
    var: nginx_status_output.stdout_lines
  when: nginx_service.failed

- name: Show Nginx error log if failed
  command: cat /var/log/nginx/error.log
  when: nginx_service.failed
  register: nginx_error_log
  ignore_errors: true

- name: Debug Nginx error log
  debug:
    var: nginx_error_log.stdout_lines
  when: nginx_service.failed
